### ISSUE TITLE
More options for config flow

### ISSUE THREAD

**Issue by leikoilja** [leikoilja/ha-google-home#124]
**Is your feature request related to a problem? Please describe.**
We currently only ask for login and password on config flow. However some people might have issue with `BadAuthentication` cause by different custom components as #95 for example. As an alternative solution we could provide `master_token` input on config UI.
Also we [discuss](https://github.com/leikoilja/ha-google-home/discussions/116) to have error catching for which we need to provide an option to 'opt out' from diagnostic data collection.

**Describe the solution you'd like**
More versatile config flow UI that allows to enter master token and opt in / opt out from diagnotic data collection

**Comment by KapJI** [comment]
I'd wait before introducing login with `master_token`. I think we can fix `gpsoauth` to be more reliable, its contributor seems to be open for improvements.

If even with this we will have `BadAuthentication` issues then we can add `master_login` in config flow.

**Comment by leikoilja** [comment]
You it not be an extra useful feature to have independent of `gpsoatuth` package? :D

**Comment by KapJI** [comment]
I think we should try to avoid to expose low level details to users.

**Comment by LEJOUI** [comment]
if I might do another suggestion. Not sure if it’s possible though. 
It would be nice if you could select which devices from GH you want to integrate. Now it just imports all of them.

**Comment by leikoilja** [comment]
@LEJOUI, of course, you are welcomed for suggestions, thanks for bringing it up to a table 💥 

We have spoken about it earlier, however, got discouraged to do so since there are soooooo many different devices that may support Google Assistant that it would quickly get painful to maintain that list. 
However, now that I think about it... there must be some ways we can still support it. 
Let me just put some thoughts down (without considering how hard/out-of-place it would be to implement them):
- we could do an initial scan after one enters his/her google credentials to discover all devices in the local network and then show another "config UI popup" where a person can select/deselect devices/
- could make a blacklist device selector on the config flow UI where one can select devices that he **does not** want to be integrated. That would enable us to maintain only "blacklist" devices, which hopefully would be a much smaller list of devices (like chromecast for example)
- could allow an optional field on the config flow UI for manually inputting device wildcard(s) (or just a list of static IP addresses). That list would take priority over "discover all devices" and only discover and use those devices that the user has manually specified. This approach would probs be for power users alone :D  

What do you guys think?

**Comment by KapJI** [comment]
I think the original question is not about supported devices list but about being able to select which supported devices to add.

So this can be a dialog with checkboxes during the config flow if you want to add all or only some devices.

But I'm not convinced if we need this because HA already provides mechanisms to disable devices on integration level or individual entities.
### Disable device
<img width="657" alt="Screenshot 2021-03-31 at 09 06 03" src="https://user-images.githubusercontent.com/3767331/113111679-547c0000-9200-11eb-8a0b-8b5c16f7a7e9.png">

### Disable entity

<img width="659" alt="Screenshot 2021-03-31 at 09 08 26" src="https://user-images.githubusercontent.com/3767331/113112054-b0468900-9200-11eb-8e66-eb932d13d855.png">

**Comment by KapJI** [comment]
Well, I think we need to fix this and don't show error messages for devices which are just turned off 🙂

**Comment by leikoilja** [comment]
It's most likely because we "cache" the devices and try fetching their related data even though the device is off, so as @KapJI  has said it's probably better we fix the log error message and using in-build mechanisms for entity disabling (@KapJI, i m on the go, could you please create a separate issue for that?)

**Comment by KapJI** [comment]
#128

**Comment by coleya** [comment]
I think it would be a useful option to allow the user to specify a `master_token` instead of the account username and app password as is suggested as best security practice in the `glocaltokens` readme. Having to store my Google account credentials on the home assistant server is the main thing keeping me from using this extension so any way around that is appreciated, this was just what I came up with to maybe achieve that.

**Comment by DurgNomis-drol** [comment]
@coleya Storing the `master_token`in plain text, as it is done in HA, is even more dangerous. The `master_token` have the ability to gain access to feature you have not even enabled on your account og you have disabled.

**Comment by leikoilja** [comment]
@coleya this is a good suggestion. 
The `glocaltokens` client already mostly supports authentication simply with `master_token`, so the only thing left is to expand the functionality of ha-google-home `config_flow` to support master token authentication without the need to login and password. I ll create corresponding issues in both repos so we can easily track and pick it up.
https://github.com/leikoilja/glocaltokens/issues/168

**Comment by DurgNomis-drol** [comment]
HA does NOT encrypt anything as far as I know. 😬😬

I am neither for or against @coleya suggestion, i just wanted to point out that it won't necessarily make this more secure. 😊

**Comment by coleya** [comment]
I am unsure about the authorization granted by the `master_token` but the app specific passwords can be used to send email which is the main point of concern for me.

**Comment by DurgNomis-drol** [comment]
@coleya ``master_token` can do literally anything to your account. It is a bad design, but that is how Google Designed it unfortunately. I would be nice if Google could make it possible to limit what the app password can do.

**Comment by coleya** [comment]
So since the app specific passwords are revokable this would actually be worse so I guess I won't be using this if you implement it.

**Comment by DurgNomis-drol** [comment]
The integration stores it anyway right now, so i won't change anything. The only reason i made the post before (And I should probably have made that more clear) was so that you didn't get lulled into false sense of security.

**Comment by coleya** [comment]
I'm glad you did, I probably won't use the integration unless I can figure out a clean way of determining who set a particular timer (this would make it worth the risk) because of the inherent security risk. I wrongly assumed that the google account security model would be more than this one token. Hopefully one day google will provide a proper api for this data and we can use tokens like for everything else.

**Comment by DurgNomis-drol** [comment]
You still access the API through the `access_token`, but you use the `master_token` to fetch this. `access_token` expires after an hour. To access each device, you use the `access_token`, to fetch the `cast-local-authorization-token``which lives about a day. The last one is then used to connect to the device. Also the `master_token` changes if you change the password.

**Comment by coleya** [comment]
Since the token changes when you change your password I assume it's tied to the app specific password it was generated with (which would have become apparent to me when I revoked it immediately after generating it which was my plan). If that's true it's even less important of a difference between the token and the password than I realized. If the token provides full control of the account then the only security using it instead would bring would be through obscurity (kinda ruined that by posting on github).

**Comment by DurgNomis-drol** [comment]
The authentication flow for Google is well known secret. What makes it secure is simply having a good password. There are also some more details that I haven't listed in my previous post surrounding how Google authenticates and so forth.

**Comment by leikoilja** [comment]
One of the cool ideas I heard from @KapJI the other day is to de-couple your google speakers / automations from your google account. Create a new secure google account for home automation things that and simply add it as a "user" to your google home. That will allow your 2nd account full access to google devices without compromising the security of your main google account :)

**Comment by KapJI** [comment]
This is how I use it since day 1. The 2nd account doesn't have access to anything other than Google Home, so even if it's hacked, it's not a huge concern for me.

@coleya Of course it's up to you if you want to use this integration. But as others said master token has the same power as username and password, so authenticating with the token doesn't really change anything but will make auth process more complex. And yes, it invalidates when you change the password.

**Comment by antonmevan** [comment]
HI I need help getting Master token for Google home
