### ISSUE TITLE
Support for GA on Sonos devices

### ISSUE THREAD

**Issue by glitchcrab** [leikoilja/ha-google-home#129]
**Is your feature request related to a problem? Please describe.**
Sonos devices with integrated GA are not discovered. This makes the integration of less use in environments with mixed devices.

**Describe the solution you'd like**
I'm not sure if this is even possible, but it would be good to also have this integration pick up timers and alarms set on GA on Sonos devices.

**Comment by leikoilja** [comment]
Uuu, that would be an interesting feature. Thou it would really require one of developers to have Sonos devices so test and implement, I am afraid I don't have any of those around :) :/ In theory it should not be hard to make: just adding extra record to `zeroconf` device discovery and making sure the API endpoints match with what google devices use :)

**Comment by DurgNomis-drol** [comment]
I believe that adding the zeroconf record should be enough. As GA API should be the same. But we need some one to test it.

Sonos zeroconf record is `_sonos._tcp.` [Referrence](https://github.com/home-assistant/core/issues/27371#issuecomment-609369903)

**Comment by glitchcrab** [comment]
If there's anything I can do to help out here (test PRs against my Sonoses etc) then please shout! I'm unlikely to be able to contribute code but I can definitely test.

**Comment by leikoilja** [comment]
@glitchcrab, as a happy owner of Sonos, do you want to help implementing it? :) We've got a bunch of supportive peps around  the team who'd be happy to review your PR and merge it in 💥

**Comment by leikoilja** [comment]
In short, all you need to do is:
- Setup dev environment (get some guidelines [here](https://github.com/leikoilja/ha-google-home/blob/master/CONTRIBUTING.md))
- Add `_sonos._tcp.` to https://github.com/leikoilja/ha-google-home/blob/3f3aae6dcba6868c26abc84b033cae75152728db/custom_components/google_home/manifest.json#L12
- Test it

**Comment by Drakulix** [comment]
I quickly tested with my sonos devices, none of them advertise `_googlerpc._tcp`, `_googlezone._tcp` and of course not `_googlecast._tcp` (since they are not google cast capable). The only thing they do advertise is `_gasetup._udp`, which is used for device discovery by google home and `_sonos._tcp` for their own local api.

They do not respond on either port `8008` nor `8443` and the `gasetup` mdns txt record does not contain any new information (like a different port). 

Listening ports appear to be 1400 and 1433 for their UPnP api (`/setup/eureka_info` returns a 404) and 1843, which seems to use TLS but either requires client certificates or is not HTTP (ssl handshake succeeds, but connection is reset before curl is sending any http requests).

This is a custom google assistant implementation (like through the google assistant sdk), which does not (and does not need to) support the google home local api. Supporting GA does not equal supporting all google home features it seems.

**Comment by KapJI** [comment]
So I think supporting Sonos devices is out of scope of this integration.

**Comment by leikoilja** [comment]
Oh, sadly, but makes sense. Thanks for investigating closer, @Drakulix 🚀

**Comment by glitchcrab** [comment]
Thanks for investigating @Drakulix - appreciate the input!

**Comment by kars85** [comment]
Apologies for reviving a stale request, but is the Sonos/GA functionality a technical limitation of the product itself with no possible HA integration for alarms/timers/etc..., or simply outside of the scope of this project? 

@Drakulix described it very well, but my layman's understanding of the packet captures has me wondering where folks with Sonos/GA devices should look for Home Assistant integration.
