### ISSUE TITLE
Add master branch protection rule.

### ISSUE THREAD

**Issue by KapJI** [leikoilja/ha-google-home#146]
**Is your feature request related to a problem? Please describe.**
Enable protection rule for `master` branch to require linting job to pass before merging the commit.
This should prevent from accidental breaking of master branch when merging before tests are finished.
Also it's nice to enable `Require linear history` and `Include administrators`, they might be already enabled.

**Describe the solution you'd like**
It can be enabled in branch settings.

https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule

<img width="1273" alt="Screenshot 2021-04-02 at 21 14 37" src="https://user-images.githubusercontent.com/3767331/113450778-72ac5080-93f8-11eb-8650-1f5bf488be42.png">

**Comment by leikoilja** [comment]
Those are some really nice protection rules. I remember really wanting to enable "Require status check to pass before merging" and it was sadly not possible at the time because of failing `HASS` checks when we had troubles with python wheels to build :) But those are all fixed now and i m happy to enable all you proposed 💥 
Donezos, thanks @KapJI 
![image](https://user-images.githubusercontent.com/10655107/113469811-e8dca180-9450-11eb-93f7-bcda73a46321.png)

**Comment by KapJI** [comment]
Looks great, thank you @leikoilja!
