### ISSUE TITLE
Add/Start a New Timer on Google Assistant

### ISSUE THREAD

**Issue by eborchardt** [leikoilja/ha-google-home#276]
I'm trying to find a way to start a timer on my Google Nest Hub from Home Assistant and found your project, which looks promising. I see I can query and delete existing timers, but is it possible to create a new one?

**Comment by ArnyminerZ** [comment]
It's possible, but not yet implemented natively. You can use the REST API at [Google Home Local API](https://rithvikvibhu.github.io/GHLocalApi/), if you know what you are doing. The integration is designed so it's more or less easy to do it.
Otherwise you can open a new issue requesting this addition, or implementing it yourself and opening a PR.
Hope this helps 😄

**Comment by leikoilja** [comment]
@ArnyminerZ which Google Home Local API endpoint were you thinking of? I was under the impression we can only GET/DELETE the alarms and timers 🤔 😅

**Comment by ArnyminerZ** [comment]
Well, didn't even search for the endpoint, just imagined that there was one 😆 

I've talked to the guys at the Google Home Local API and they told me that the endpoints were a bit outdated, so maybe there's an alarm-create one that we don't know of, which should make sense. But since we can no longer add alarms from the Google Home app (I don't know if it was possible before). Maybe this is work that should be done by Google.

**Comment by KapJI** [comment]
I don't think such endpoint exists because Google Home app doesn't provide this functionality. I think they intentionally want it only to be available with voice commands.
