### ISSUE TITLE
Simplify manual installation

### ISSUE THREAD

**Issue by KapJI** [leikoilja/ha-google-home#44]
**Is your feature request related to a problem? Please describe.**
Copying files from repo folder to `custom_components` is not very convenient.

**Describe the solution you'd like**
I think it'd be much simpler if repo can be just cloden inside `custom_components` without any extra actions. This will simplify interating for contributor as well.

It just needs putting `__init__.py` in the repo root, all other sources can be placed in subfolder for cleaner repo structure.

**Comment by leikoilja** [comment]
Hey, @KapJI. Thanks for the issue. We are currently working on integrating it into HACS, so it will soon be available for a simpler installation.

For some insights how to install it simpler please see here - https://github.com/leikoilja/ha-google-home/discussions/23#discussioncomment-420354 , but note that `master` is currently broken 😢 

I'll close this issue for now, because it's not adding any value. 
Feel free to reopen if you think otherwise.
