### ISSUE TITLE
Integration needs to be reloaded every now and then

### ISSUE THREAD

**Issue by Hellis81** [leikoilja/ha-google-home#445]
## Describe the bug

Sometimes when I set a timer the sensor does not "notice" it. 
If I reload the integration it sees the timer. 

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
1.9.4
```

## Logs

```text
Don't have any logs.
```

But as a question/workaround, How often does the auth_token update? 
I could perhaps set up an automation to reload the automation when the token is frozen (I assume this stays frozen when the sensors don't respond).

**Comment by leikoilja** [comment]
Hey, @Hellis81. 
In theory, you should not be worried about auth_token and it's update, since the package should automatically request an update of the tokens if those are found stale (typically once in 24h that should happen). 
The integration has a default of 3minutes for an update interval. When you set your timer/alarm do they not appear in the sensors after 3+ minutes? 
We would probably need more logs to understand what happens and why your integration does not load the data from the devices. The logs can help us inspect and understand if something is failing during API calls

**Comment by Hellis81** [comment]
I can't test the issue, since this issue is not an issue currently. Because of that I don't have any logs showing that it doesn't work.
Right now everything works fine, but during the last year it has happend four-five times that It had not worked and I had to reaload the integration.
That is why I thought I could perhaps use the auth token as the trigger.
I created a sensor on the auth token and in my case it seems to update every morning at about 4. Perhaps this will change later, but I will keep an eye on this and see if this is a potential trigger for a reload.

But yes the timers are longer than three minutes.

**Comment by Leatherface75** [comment]
For me timers/alarms isn't working at all anymore.

**Comment by leikoilja** [comment]
@Leatherface75, please open a new issue with logs if you want some help reolving it :)

**Comment by Leatherface75** [comment]
> @Leatherface75, please open a new issue with logs if you want some help reolving it :)

Nevermind i uninstalled and reinstalled and then it worked again. Strange.

**Comment by ArnyminerZ** [comment]
Seems to be fixed. Reopen if more info is required.
