### ISSUE TITLE
Relax requirements for account name

### ISSUE THREAD

**Issue by KapJI** [leikoilja/ha-google-home#45]
**Is your feature request related to a problem? Please describe.**
Requiring stripping of `@gmail.com` is too restrictive. Also note that Google accounts can be on custom domains with G Suite and they probably also should be supported.

**Describe the solution you'd like**
This can be done programatically.

**Comment by KapJI** [comment]
It's not clear where this requirement is coming from in the first place because `perform_master_login` clearly expects email (and it works): https://github.com/simon-weber/gpsoauth/blob/master/gpsoauth/__init__.py#L65

**Comment by leikoilja** [comment]
Thanks for a good insight, @KapJI. We should defs drop the `@gmal.com` requirement and simply keep it as email address.
Will add it as "TODO", but If you have skills and interest and feel like contributing - please drop the PR! 💥

**Comment by ArnyminerZ** [comment]
I believe `@gmail.com` could be used, and the log in should still be valid, since it's not getting added anywhere, as far as I see.
In [`glocaltokens`](https://github.com/leikoilja/glocaltokens/blob/master/glocaltokens/client.py#L102), it's detailed that it shouldn't be added, but then it calls [`perform_oauth`](https://github.com/simon-weber/gpsoauth/blob/master/gpsoauth/__init__.py#L107) from `gpsoauth`, which uses [`_perform_auth_request`](https://github.com/simon-weber/gpsoauth/blob/a7daa9250468161a44819e33e1eec8721b32e983/gpsoauth/__init__.py#L53), which simply makes the request to Google, so I suppose it should use the same method as the Google page login.

**Comment by KapJI** [comment]
Yes, I think both can be used but there is no reason to ask users to remove `@gmail.com`.

**Comment by ArnyminerZ** [comment]
Yes, I think somebody could test if it works with `@gmail.com`, and if it does, simply remove the warning.

**Comment by KapJI** [comment]
I tested and it works :)

**Comment by leikoilja** [comment]
You are right, @KapJI. Gmail also has Gsuit that allows people to have google mails with a whole different alias ending. It can by literally anything like `user@gmail.com` or `user@mycompany.com` where both would point to google services. By stripping `gmail` and then programmatically adding - it locks us to only support `gmail` domains, that does not make sense, since both should be supported ;)

**Comment by ArnyminerZ** [comment]
> 
> 
> I tested and it works :)

Awesome! Opening a PR on that.
