### ISSUE TITLE
Can't add google home device that are linked services

### ISSUE THREAD

**Issue by Th0masDB** [leikoilja/ha-google-home#510]
**Is your feature request related to a problem? Please describe.**
I have the same problem as in #287. The problem for me is that there is no other way to get my lights in Home Assistant. (Unfortunately, my house came with [Enet](https://www.enet-smarthome.com/nl/). 

**Describe the solution you'd like**
That it would be possible to also see linked service's trough Google Home in Home Assistant.

**Describe alternatives you've considered**
Not applicable in this case.

**Additional context**
![Screenshot from 2022-04-10 18-55-01](https://user-images.githubusercontent.com/12988955/162630645-479855d2-471e-451d-a7f8-458d3bdc4db2.png)

Already thanks!

**Comment by ArnyminerZ** [comment]
I'm using linked services in my Google Home setup, however, I think that adding all of that to this integration may cause duplicity issues, and would be quite a huge project for ourselves. Instead, I think a new integration for Enet might be the best option, just like Tuya or Philips Hue have their own integrations.

I don't even think it's actually possible to control those devices easily without having to redo most of the integration. We had this discussion a long time ago, but since we are using the "non-google-supported" Homegraph API, I believe this control is not possible. Changing this would mean changing the authentication method used by the integration, as well as all the device controls.

However, something that we might have to do is to clarify somewhere in the README that this integration is only compatible with the Google Home smart speakers, not the other IoT and home automation devices.

Feel free to correct me if I'm wrong, but I think that was the investigation we did at the time of thinking about changing the SDK used.

**Comment by leikoilja** [comment]
That's right, that's right. Having separate integrations per device group like 'enet', 'tuya', 'philips' etc makes it a lot easier to manage, especially if these devices have device-specific feature set.

Maybe we should just do what @ArnyminerZ suggests and write down this integration limitations in README? :)

**Comment by Th0masDB** [comment]
Fair enough. :)

**Comment by Th0masDB** [comment]
> 

My programming skills are not that great unfortunately :(
