### ISSUE TITLE
Google sign in not working

### ISSUE THREAD

**Issue by mossychop** [leikoilja/ha-google-home#747]
## Describe the bug

Unable to sign in using app passwords or account with no 2fa enabled.

Error just shows 

Username/Password is incorrect. If your google account has 2FA enabled please generate app password (https://myaccount.google.com/apppasswords). If authentication still fails refer to https://github.com/leikoilja/ha-google-home#troubleshooting

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
1.10
```

## Logs

```text
Add your logs here.
```

**Comment by leikoilja** [comment]
@mossychop, please check [Troubleshooting](https://github.com/leikoilja/ha-google-home#troubleshooting) section, especially regarding [app password](https://github.com/leikoilja/ha-google-home#usernamepassword-is-incorrect). 
Also, please see [this thread](https://github.com/leikoilja/ha-google-home/issues/599), since there are known issues even with app-passwords due to Google randomly blocking user requests. Best approach for you is to get `master_token` in isolation and then use this integration using the `master_token` instead of username/passowrd

**Comment by mossychop** [comment]
Thanks for the help - I have been through all of the troubleshooting (which is pages and pages linking to other pages). The only solution seems to be to get the master_token which I have followed the instructions and don't seem to have python on my Windows machine, this is a bit beyond my skills. 

I have tried multiple google accounts with and without 2FA enabled. Happy to provide whatever logs needed - I've lost a few hours on this so any help appreciated.
