### ISSUE TITLE
docker container script for credentials not working

### ISSUE THREAD

**Issue by snickers2k** [leikoilja/ha-google-home#787]
[*] Getting master token...
[!] Could not get master token.
[*] Master token: None

[*] Getting access token...
[!] Could not get access token.
[*] Access token: None

[*] Done.

**Comment by rensdebee** [comment]
Same for me.
Is the app password supposed to include spaces or not, tried with and without both failed

**Comment by KapJI** [comment]
@Brephlas looks like new alpine image doesn't work. Also if you have some time, can you verify and document this method as well?
https://github.com/rukins/gpsoauth-java#receiving-an-authentication-token

**Comment by Brephlas** [comment]
Oh that should not have happened. I've updated the repo and the image on dockerhub back to debian. `CMD` is still set to `python3 get_tokens.py` so the documented command to run the container stays the same

@KapJI not sure if we want to also implement this. If we want, I'd add this in a separate container to reduce image size (since java is required). But I dont really see the point if we have a working solution 🤔

**Comment by KapJI** [comment]
@Brephlas I mean not Java impregnation but manual steps with using cookies.

**Comment by Brephlas** [comment]
Since the Dockerfile as well as the docker container are reverted back into working state, I think this issue can be closed. Maybe @snickers2k can you confirm that it is working for you? 


@KapJI not sure if i understand correctly, but you mean using the cookies inside the current python implementation `get_tokens.py`? Guess this would require using the Java implementation since the python gpsoauth does only use username + password https://github.com/simon-weber/gpsoauth/blob/6571ae307aa0d224d64a2fd265367d3d2ce4f589/gpsoauth/__init__.py#L102

**Comment by KapJI** [comment]
@Brephlas I mean that they claim it's possible to get master token manually from cookies without any scripts or containers. Worth checking.

**Comment by lipigab** [comment]
> [_] Getting master token... [!] Could not get master token. [_] Master token: None
> 
> [_] Getting access token... [!] Could not get access token. [_] Access token: None
> 
> [*] Done.

Had the same issue first, but then I created an new App Password and I was able to generate the token successfully.
